language: android

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

components:
  - android-26

# configuration options: https://docs.travis-ci.com/user/languages/android/
