language: android

sudo: required

android: 
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository

script:
  - ./gradlew build test

# configuration options: https://docs.travis-ci.com/user/languages/android/
